### ISSUE TITLE
How to make a request?

### ISSUE THREAD

**Issue by debe13** [robbietjuh/py-bricklink#2]
Hi,

I am new to python and I want to use this module to connect to the BrickLink API. In my specific example I want to make a GET /inventories request. How does that work exactly? 

1. I place the 'BrickLink' folder in 'Lib'
2. I replace the values in the _init_ with my API data from BrickLink
3. I run api.py

Is this the right approach or do I have to write another program to make the actual request? 

Any help is appreciated!

**Comment by robbietjuh** [comment]
Hi debe13. I see you're new to Github, welcome!

You can use `py-bricklink` to communicate with the BrickLink API through Python. `py-bricklink` is a library and should therefor be used in combination with your own application code. You can use `py-bricklink` by putting it in your lib folder, as you mentioned before, and importing it in your own code. In Python, you can use modules, or libraries, by importing them to your application code. Put simply, it's to let Python know what 3rd party code to speak to.

Also, don't forget to install the dependencies at noted in requirements.txt. If you have pip installed, simply run `pip install -r requirements.txt`

You can try running this sample code:

```python
# Fill these in yourself
consumer_key = "..."
consumer_secret = "..."
access_token = "..."
access_token_secret = "..."

# Import the py-bricklink lib and set up a connection with Bricklink
from bricklink import ApiClient
api = ApiClient(consumer_key, consumer_secret, access_token, access_token_secret)

# Fetch your inventory (GET /inventories)
api.inventory.getInventories()
```

Let me know if you have any other questions.

**Comment by debe13** [comment]
wow that was fast... thx a lot. So I ran the prgoramm and it runs for a while and finishes with exit code 0.So I guess it worked since I gave no further commands for processing the data.

What do I do next? Do I have to define a variable that is equal to the requests response? How do I work with the data? I am just starting to write code and learn python. If you could tell me how I can tap into the data that would be great!

**Comment by robbietjuh** [comment]
You can indeed save the result from your query to a variable or a file, for that matter. Try running python in your terminal (or cmd.exe if you're using Windows). It'll enable you to experiment with your code as you can execute commands as you type them.

If you're trying to simply write the contents of your inventory to a temporary file in order to create a backup, you may want to run something like this:

```python
# Dependencies
import json
from datetime import datetime
from bricklink import ApiClient

# Fill these in yourself
consumer_key = "..."
consumer_secret = "..."
access_token = "..."
access_token_secret = "..."
filename = "Bricklink backup"

# Set up a connection with Bricklink
api = ApiClient(consumer_key, consumer_secret, access_token, access_token_secret)

# Fetch your inventory (GET /inventories)
inventory = api.inventory.getInventories()

# Put together a filename to store your backup in
date = datetime.now().strftime('%Y-%m-%d %H-%M')
filename = "%s [%s].json" % (filename, date)

# Write to the file
with open(filename, 'w') as outfile:
    json.dump(inventory, outfile)

# Report to the terminal
print("All done!")
```

**Comment by debe13** [comment]
Hi again,

thx a lot for the help. It works fine. I will try to make the output file BrickLink compatible in the next few days, but the data is there. This community is really great for beginners like me thx to pros like you!

**Comment by robbietjuh** [comment]
Thanks for the kind words. I'm glad I could be of help.
