### ISSUE TITLE
Re-uploading a backed up inventory

### ISSUE THREAD

**Issue by debe13** [robbietjuh/py-bricklink#3]
Hi Robbie,

it's me again. Since you know BrickLink and Python very well, I wanted to ask you if you would be so kind to look into the following issue, eventhough it is not really related to your module:

I am looking for an inventory backup of our shop that can be reuploaded to BrickLink, but getting the .json file from the GET /inventories request into the right xml-standard is quite hard. Since there is an inventory download on Bricklink in the right format, I changed my approach from using the API to scraping... if that is the correct term. :)

So far I managed to login successfully under Python 2.7 using requests with the following code:

------------------------------
import requests

with requests.Session() as c:
    url = 'https://www.bricklink.com/login.asp?logInTo=&logFolder=p&logSub=w'
    USERNAME = '.....'
    PASSWORD = '.....'
    c.get(url)
    login_data = dict(frmUsername=USERNAME, frmPassword=PASSWORD, a='a')
    c.post(url, data=login_data, headers={"Referer": "https://www.bricklink.com/login.asp"})

page = c.get('http://www.bricklink.com/invExcel.asp')
print page.content

------------------------------

I end up at the get page, so I guess the login was successfull. Then I wanted to make a similar request to the form on  BrickLink witch gives out the file download I need as a response. However, this post request does not work with form data only, probably due to cookie protection!? Here is what Chrome shows me when I send the post request manually:

    General
        Remote Address:
        54.208.56.110:80
        Request URL:
        http://www.bricklink.com/invExcelFinal.asp?
        Request Method:
        POST
        Status Code:
        200 OK
    Response Headersview source
        Cache-Control:
        private
        Connection:
        close
        Content-Disposition:
        attachment; filename=invxml.txt;
        Content-Type:
        text/xml;charset=UTF-8
        Date:
        Fri, 17 Apr 2015 01:49:05 GMT
        Server:
        Microsoft-IIS/7.5
        Set-Cookie:
        lngOpt=1; expires=Sun, 17-May-2015 01:49:04 GMT; path=/
        Set-Cookie:
        isCountryID=DE; path=/
        Set-Cookie:
        BLalertCnt=1184; domain=bricklink.com; path=/
        Set-Cookie:
        BLdiscussFlag=; domain=bricklink.com; path=/
        Set-Cookie:
        viewCurrencyID=2; path=/
        X-Powered-By:
        ASP.NET
    Request Headersview source
        Accept:
        text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
        Accept-Encoding:
        gzip, deflate
        Accept-Language:
        de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4
        Cache-Control:
        max-age=0
        Connection:
        keep-alive
        Content-Length:
        111
        Content-Type:
        application/x-www-form-urlencoded
        Cookie:
        catalogView=cView=1; is_returning=1; xxxx=xxxx; _gat=1; isPw=; isType=; isLoggedInAs=; rememberMe=; isUserID=; BLAUTHACCOUNT=202103; _ga=GA1.2.1196042763.1422431124; lngOpt=1; isCountryID=DE; BLalertCnt=1184; BLdiscussFlag=; viewCurrencyID=2
        Host:
        www.bricklink.com
        Origin:
        http://www.bricklink.com
        Referer:
        http://www.bricklink.com/invExcel.asp
        User-Agent:
        Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36
    Form Dataview sourceview URL encoded
        dialogBox:
        viewType:
        x
        invStock:
        Y
        invQtyMin:
        0
        invQtyMax:
        0
        itemType:
        catID:
        colorID:
        invNew:
        itemYear:
        q:
        rmkTp:
        W

How should I proceed? Do I have to get other modules like cookielib or something like that?

thx in advance and best regards,

Dennis

**Comment by robbietjuh** [comment]
First of all, sorry for responding a bit late.

You can use the code from issue #1 and use `api.inventory.createInventory(bl_resource)` to create a new lot. Have a look at the following code. You cannot use it by copy-pasting it, but it should give you an idea on how to use the `createInventory` API (I use it in production for a customer of mine):

```python
       api = ApiClient() # Replace with bootstrap code from issue 1

        # Lot data
        bl_resource = {
            'item': {'no': self.lego_id, 'type': self.full_type},
            'quantity': self.quantity,
            'unit_price': str(self.lego_price),
            'new_or_used': self.lego_condition,
            'description': self.lego_comment,
            'remarks': 'GBCRM_BL_API 1.1 LOT_STAGE3_NEW',
            'bulk': 1,
            'is_retain': False,
            'is_stock_room': False,
        }

        if self.lego_colour is not None:
            bl_resource['color_id'] = self.lego_colour.bricklink_id
        else:
            bl_resource['color_id'] = 0

        if self.type == 'S':
            bl_resource['completeness'] = 'C'

        bl_response = api.inventory.createInventory(bl_resource)
